apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
{{ include "mongodb.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongo-port
      protocol: TCP
      name: mongo-port
  selector:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
