{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "recolector.serviceAccountName" . }}
  labels:
{{ include "recolector.labels" . | indent 4 }}
{{- end -}}
