{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rabbitmq.serviceAccountName" . }}
  labels:
{{ include "rabbitmq.labels" . | indent 4 }}
{{- end -}}
